# Generated by Django 2.0.8 on 2018-09-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiu_app', '0003_auto_20180930_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='redirect_url',
            field=models.URLField(default=None, null=True, verbose_name='Where do you want the "Learn More" button to go?'),
        ),
    ]
