# Generated by Django 2.0.8 on 2018-09-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiu_app', '0005_auto_20180930_1912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='HomePageDescription',
        ),
    ]
