# Generated by Django 2.0.8 on 2018-09-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiu_app', '0006_auto_20180930_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img/addons/'),
        ),
    ]
