# Generated by Django 2.0.8 on 2018-10-06 15:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('fiu_app', '0007_auto_20180930_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=tinymce.models.HTMLField(help_text="This won't be displayed to the vistor, but it will be used as metadata, which improves SEO."),
        ),
        migrations.AlterField(
            model_name='photo',
            name='gallery',
            field=models.ManyToManyField(help_text='You can create galleries that contain groups of photos ~ facilities, staff, etc', to='fiu_app.Gallery'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(help_text='Upload a photo', upload_to='img/%m/%d', verbose_name='My Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(help_text='The image title.', max_length=100),
        ),
    ]
