# Generated by Django 2.0.8 on 2018-10-06 15:44

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('fiu_app', '0008_auto_20181006_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='The image description. Displayed as subtext associated with the linked photo.', null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(help_text='Upload a photo', upload_to='media/img/%m/%d', verbose_name='My Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, help_text='The image title. This is used as metadeta to imporve SEO.', max_length=100, null=True),
        ),
    ]
