# Generated by Django 2.0.8 on 2018-10-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiu_app', '0009_auto_20181006_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(help_text='Upload a photo', upload_to='media/img/%y/%m/%d', verbose_name='My Photo'),
        ),
    ]
