# Generated by Django 2.0.8 on 2018-12-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiu_app', '0013_auto_20181013_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
